# 项目名
name: neta-render

# 只有在master分支发生push事件时触发
on:
  push:
    branches:
      - main

# 工作流
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 运行环境

    steps:
      # 拉代码
      - name: Checkout code
        uses: actions/checkout@v1

      # 下载node，我这里指定了15.x，这个版本可随意，高于dumi规定的node版本即可
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      # 打包代码
      - name: Build Project
        run: |
          npm install
          npm run docs:build
      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      # 部署到github
      - name: Deploy to Github
        uses: crazy-max/ghaction-github-pages@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_SECERT }}
        with:
          # 部署到 s-pages 分支
          target_branch: gh-pages # 打包的内容放到build分支下
          # 部署目录的默认输出目录
          build_dir: docs-dist